# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment',
            field=models.CharField(choices=[('CC', 'CC'), ('DC', 'DC'), ('CS', 'CS'), ('PY', 'PY')], max_length=2, null=True),
        ),
    ]
