# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.Cart'),
            preserve_default=False,
        ),
    ]
