# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170430_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units_aviable',
            field=models.IntegerField(default=0),
        ),
    ]
