# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20170514_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('neighborhood', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=180)),
                ('state', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='appuser',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.CharField(choices=[('CK', 'CK'), ('CC', 'CC'), ('DC', 'DC'), ('CS', 'CS'), ('PY', 'PY')], max_length=2, null=True),
        ),
    ]
